name: EntitySpawnManager
main: de.msm.main.MobSpawnManager
website: https://discord.gg/yhBX6KT
version: 1.3.3
api-version: 1.16
author: GibMirRechte
authors:
   - _ProfliX_
commands:
   managegui:
      description: Edit the config.yml without open it
